<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H6V4GD0" failures="1" tests="1" name="Test(failed)" time="5.468" errors="0" timestamp="2024-05-16T20:44:07 IST">
  <testcase classname="com.standalone.SauceInvalidLoginTest" name="invalidLoginTest" time="1.466">
    <failure type="java.lang.AssertionError" message="Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.dsd] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.dsd] but found [Epic sadface: Sorry, this user has been locked out.]
at com.standalone.SauceInvalidLoginTest.invalidLoginTest(SauceInvalidLoginTest.java:16)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest -->
</testsuite> <!-- Test(failed) -->
