<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Old report backed up to folder D:\Development\Eclipse-Workspaces\WithRituRaj\TestFramework2\Test-Reports//20May24_20.23.38.426//]]>
    </line>
  </reporter-output>
  <suite started-at="2024-05-20T20:23:38 IST" name="Suite" finished-at="2024-05-20T20:23:49 IST" duration-ms="10210">
    <groups>
    </groups>
    <test started-at="2024-05-20T20:23:38 IST" name="Test" finished-at="2024-05-20T20:23:49 IST" duration-ms="10210">
      <class name="com.tests.SauceInvalidLoginTest">
        <test-method is-config="true" signature="preSuite()[pri:0, instance:com.tests.SauceInvalidLoginTest@393671df]" started-at="2024-05-20T20:23:38 IST" name="preSuite" finished-at="2024-05-20T20:23:38 IST" duration-ms="399" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Old report backed up to folder D:\Development\Eclipse-Workspaces\WithRituRaj\TestFramework2\Test-Reports//20May24_20.23.38.426//]]>
            </line>
          </reporter-output>
        </test-method> <!-- preSuite -->
        <test-method is-config="true" signature="init()[pri:0, instance:com.tests.SauceInvalidLoginTest@393671df]" started-at="2024-05-20T20:23:38 IST" name="init" finished-at="2024-05-20T20:23:44 IST" duration-ms="5954" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="invalidLoginTest()[pri:0, instance:com.tests.SauceInvalidLoginTest@393671df]" started-at="2024-05-20T20:23:44 IST" name="invalidLoginTest" finished-at="2024-05-20T20:23:47 IST" duration-ms="2690" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.XYZ] but found [Epic sadface: Sorry, this user has been locked out.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.XYZ] but found [Epic sadface: Sorry, this user has been locked out.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.tests.SauceInvalidLoginTest.invalidLoginTest(SauceInvalidLoginTest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SauceInvalidLoginTest@393671df]" started-at="2024-05-20T20:23:47 IST" name="tearDown" finished-at="2024-05-20T20:23:48 IST" duration-ms="650" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.SauceInvalidLoginTest -->
      <class name="com.tests.SauceValidLoginTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.tests.SauceValidLoginTest@1ab3a8c8]" started-at="2024-05-20T20:23:38 IST" name="init" finished-at="2024-05-20T20:23:43 IST" duration-ms="4815" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="invalidLoginTest()[pri:0, instance:com.tests.SauceValidLoginTest@1ab3a8c8]" started-at="2024-05-20T20:23:43 IST" name="invalidLoginTest" finished-at="2024-05-20T20:23:48 IST" duration-ms="4769" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tests.SauceValidLoginTest@1ab3a8c8]" started-at="2024-05-20T20:23:48 IST" name="tearDown" finished-at="2024-05-20T20:23:49 IST" duration-ms="591" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.SauceValidLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
