<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-H6V4GD0" failures="1" tests="2" name="Test" time="10.21" errors="0" timestamp="2024-05-20T20:23:49 IST">
  <testcase classname="com.tests.SauceInvalidLoginTest" name="invalidLoginTest" time="2.69">
    <failure type="java.lang.AssertionError" message="Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.XYZ] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.XYZ] but found [Epic sadface: Sorry, this user has been locked out.]
at com.tests.SauceInvalidLoginTest.invalidLoginTest(SauceInvalidLoginTest.java:16)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest -->
  <testcase classname="com.tests.SauceValidLoginTest" name="invalidLoginTest" time="4.769"/>
  <testcase classname="com.tests.BaseTest" name="@BeforeSuite preSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite preSuite -->
</testsuite> <!-- Test -->
